---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  trailing-spaces: enable
  indentation:
    spaces: 2
    indent-sequences: true

ignore: |
  node_modules/
  dist/
  .github/
